-- Crear el usuario ADMIN por defecto en auth.users
INSERT INTO auth.users (
  id,
  instance_id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_token_current,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at,
  is_anonymous
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  '00000000-0000-0000-0000-000000000000',
  'authenticated',
  'authenticated',
  'jguiller412@gmail.com',
  crypt('MeDAp3na', gen_salt('bf')),
  now(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  now(),
  '{"provider": "email", "providers": ["email"]}',
  '{}',
  FALSE,
  now(),
  now(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  '',
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL,
  FALSE
) ON CONFLICT (id) DO NOTHING;

-- Crear el registro en public.users con el rol 'admin'
INSERT INTO public.users (
  id,
  email,
  full_name,
  username,
  role,
  onboarded,
  created_at,
  updated_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  'jguiller412@gmail.com',
  'José Guillermo Vásquez',
  'joselito412',
  'admin',
  true,
  now(),
  now()
) ON CONFLICT (id) DO NOTHING;
